[2023-05-10 05:03:58,944] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: feature_engineering_dag.stock_csv_to_parquet manual__2023-05-10T05:03:52.276459+00:00 [queued]>
[2023-05-10 05:03:59,049] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: feature_engineering_dag.stock_csv_to_parquet manual__2023-05-10T05:03:52.276459+00:00 [queued]>
[2023-05-10 05:03:59,049] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 05:03:59,049] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-05-10 05:03:59,050] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 05:03:59,153] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): stock_csv_to_parquet> on 2023-05-10 05:03:52.276459+00:00
[2023-05-10 05:03:59,159] {standard_task_runner.py:52} INFO - Started process 20265 to run task
[2023-05-10 05:03:59,175] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'feature_engineering_dag', 'stock_csv_to_parquet', 'manual__2023-05-10T05:03:52.276459+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/feature_engineering_dag.py', '--cfg-path', '/tmp/tmpf0sovrj4', '--error-file', '/tmp/tmp14_zvt57']
[2023-05-10 05:03:59,176] {standard_task_runner.py:77} INFO - Job 148: Subtask stock_csv_to_parquet
[2023-05-10 05:03:59,446] {logging_mixin.py:109} INFO - Running <TaskInstance: feature_engineering_dag.stock_csv_to_parquet manual__2023-05-10T05:03:52.276459+00:00 [running]> on host cd79de2e36bd
[2023-05-10 05:03:59,782] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=feature_engineering_dag
AIRFLOW_CTX_TASK_ID=stock_csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2023-05-10T05:03:52.276459+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-10T05:03:52.276459+00:00
[2023-05-10 05:03:59,795] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/feature_engineering.py", line 99, in stock_csv_to_parquet
    for file in os.listdir(csv_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/stage/stocks/'
[2023-05-10 05:03:59,890] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=feature_engineering_dag, task_id=stock_csv_to_parquet, execution_date=20230510T050352, start_date=20230510T050358, end_date=20230510T050359
[2023-05-10 05:04:00,017] {standard_task_runner.py:92} ERROR - Failed to execute job 148 for task stock_csv_to_parquet
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/feature_engineering.py", line 99, in stock_csv_to_parquet
    for file in os.listdir(csv_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/stage/stocks/'
[2023-05-10 05:04:00,143] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-05-10 05:04:00,237] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
