[2023-05-10 03:56:51,427] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_processing_dag.stock_csv_to_parquet manual__2023-05-09T06:21:48.264367+00:00 [queued]>
[2023-05-10 03:56:51,738] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_processing_dag.stock_csv_to_parquet manual__2023-05-09T06:21:48.264367+00:00 [queued]>
[2023-05-10 03:56:51,739] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 03:56:51,739] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-05-10 03:56:51,740] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-10 03:56:51,879] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): stock_csv_to_parquet> on 2023-05-09 06:21:48.287385+00:00
[2023-05-10 03:56:51,900] {standard_task_runner.py:52} INFO - Started process 1452 to run task
[2023-05-10 03:56:51,969] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_processing_dag', 'stock_csv_to_parquet', 'manual__2023-05-09T06:21:48.264367+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_dag.py', '--cfg-path', '/tmp/tmpyspty6tp', '--error-file', '/tmp/tmpaxv18n96']
[2023-05-10 03:56:51,982] {standard_task_runner.py:77} INFO - Job 122: Subtask stock_csv_to_parquet
[2023-05-10 03:56:52,719] {logging_mixin.py:109} INFO - Running <TaskInstance: data_processing_dag.stock_csv_to_parquet manual__2023-05-09T06:21:48.264367+00:00 [running]> on host cd79de2e36bd
[2023-05-10 03:56:53,291] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_processing_dag
AIRFLOW_CTX_TASK_ID=stock_csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2023-05-09T06:21:48.287385+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-09T06:21:48.264367+00:00
[2023-05-10 03:56:53,400] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-05-10 03:56:53,402] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2023-05-10 03:56:53,415] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2023-05-10 03:56:53,429] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2023-05-10 03:56:53,432] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2023-05-10 03:56:53,446] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2023-05-10 03:56:53,449] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2023-05-10 03:56:53,462] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2023-05-10 03:56:53,464] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2023-05-10 03:56:53,478] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2023-05-10 03:56:53,481] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2023-05-10 03:56:53,495] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2023-05-10 03:56:53,495] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_processing_dag.py", line 40, in run_callable_multiprocess
    p.start()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 110, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
[2023-05-10 03:56:53,599] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_processing_dag, task_id=stock_csv_to_parquet, execution_date=20230509T062148, start_date=20230510T035651, end_date=20230510T035653
[2023-05-10 03:56:53,808] {standard_task_runner.py:92} ERROR - Failed to execute job 122 for task stock_csv_to_parquet
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_processing_dag.py", line 40, in run_callable_multiprocess
    p.start()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 110, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
[2023-05-10 03:56:53,860] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-05-10 03:56:55,556] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
